ASpecialDay/Models/GiftList.cs
using ASpecialDay.Areas.Identity.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ASpecialDay.Models
{
    public class GiftList
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        public string InviteCode { get; set; }

        public virtual Bride Bride { get; set; }
        public virtual ICollection<Gift> Gifts { get; set; }
        public virtual ICollection<Guest> Guests { get; set; }
        public virtual ICollection<BoughtBy> Boughts { get; set; }
    }
}

ASpecialDay/Pages/CRUD/_GiftList/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ASpecialDay.Areas.Identity.Data;
using ASpecialDay.Models;

namespace ASpecialDay.Pages.CRUD._GiftList
{
    public class CreateModel : PageModel
    {
        private readonly ASpecialDay.Areas.Identity.Data.ASpecialDayContext _context;

        public CreateModel(ASpecialDay.Areas.Identity.Data.ASpecialDayContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public GiftList GiftList { get; set; }

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.GiftLists.Add(GiftList);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

ASpecialDay/Pages/CRUD/_GiftList/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ASpecialDay.Areas.Identity.Data;
using ASpecialDay.Models;

namespace ASpecialDay.Pages.CRUD._GiftList
{
    public class DeleteModel : PageModel
    {
        private readonly ASpecialDay.Areas.Identity.Data.ASpecialDayContext _context;

        public DeleteModel(ASpecialDay.Areas.Identity.Data.ASpecialDayContext context)
        {
            _context = context;
        }

        [BindProperty]
        public GiftList GiftList { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            GiftList = await _context.GiftLists.FirstOrDefaultAsync(m => m.InviteCode == id);

            if (GiftList == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            GiftList = await _context.GiftLists.FindAsync(id);

            if (GiftList != null)
            {
                _context.GiftLists.Remove(GiftList);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

ASpecialDay/Pages/CRUD/_GiftList/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ASpecialDay.Areas.Identity.Data;
using ASpecialDay.Models;

namespace ASpecialDay.Pages.CRUD._GiftList
{
    public class DetailsModel : PageModel
    {
        private readonly ASpecialDay.Areas.Identity.Data.ASpecialDayContext _context;

        public DetailsModel(ASpecialDay.Areas.Identity.Data.ASpecialDayContext context)
        {
            _context = context;
        }

        public GiftList GiftList { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            GiftList = await _context.GiftLists.FirstOrDefaultAsync(m => m.InviteCode == id);

            if (GiftList == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

ASpecialDay/Pages/CRUD/_GiftList/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASpecialDay.Areas.Identity.Data;
using ASpecialDay.Models;

namespace ASpecialDay.Pages.CRUD._GiftList
{
    public class EditModel : PageModel
    {
        private readonly ASpecialDay.Areas.Identity.Data.ASpecialDayContext _context;

        public EditModel(ASpecialDay.Areas.Identity.Data.ASpecialDayContext context)
        {
            _context = context;
        }

        [BindProperty]
        public GiftList GiftList { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            GiftList = await _context.GiftLists.FirstOrDefaultAsync(m => m.InviteCode == id);

            if (GiftList == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(GiftList).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!GiftListExists(GiftList.InviteCode))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool GiftListExists(string id)
        {
            return _context.GiftLists.Any(e => e.InviteCode == id);
        }
    }
}

ASpecialDay/Pages/CRUD/_GiftList/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ASpecialDay.Areas.Identity.Data;
using ASpecialDay.Models;

namespace ASpecialDay.Pages.CRUD._GiftList
{
    public class IndexModel : PageModel
    {
        private readonly ASpecialDay.Areas.Identity.Data.ASpecialDayContext _context;

        public IndexModel(ASpecialDay.Areas.Identity.Data.ASpecialDayContext context)
        {
            _context = context;
        }

        public IList<GiftList> GiftList { get;set; }

        public async Task OnGetAsync()
        {
            GiftList = await _context.GiftLists.ToListAsync();
        }
    }
}

ASpecialDay/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ASpecialDay.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ASpecialDay/Pages/GiftList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASpecialDay.Areas.Identity.Data;
using ASpecialDay.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASpecialDay.Pages
{
    public class GiftListModel : PageModel
    {
        private readonly ASpecialDayContext _context;
        private readonly SignInManager<Bride> _signInManager;
        private readonly UserManager<Bride> _userManager;

        [BindProperty] public GiftList _GiftList { get; set; }
        [BindProperty] public Gift NewGift { get; set; } = new Gift();
        [BindProperty] public string InviteCode { get; set; }

        public GiftListModel(ASpecialDayContext context, SignInManager<Bride> signInManager, UserManager<Bride> userManager)
        {
            _context = context;
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public async Task<IActionResult> OnGetAsync(string inviteCode)
        {
            InviteCode = inviteCode;
            GiftList giftList = _context.GiftLists.Where(_giftList => _giftList.InviteCode == inviteCode).First();

            Bride loggedInUser = await _userManager.GetUserAsync(User);
            if (giftList != null && (!_signInManager.IsSignedIn(User) || (_signInManager.IsSignedIn(User) && giftList.Bride == loggedInUser)))
            {
                _GiftList = giftList;
                if (_GiftList.Gifts != null)
                {
                    _GiftList.Gifts = (ICollection<Gift>)_GiftList.Gifts.OrderBy(_gift => _gift.Position);
                }
                return Page();
            }
            else
            {
                return NotFound();
            }
        }

        public IActionResult OnPostAddGift(string inviteCode)
        {
            if (ModelState.IsValid)
            {
                int calculatedPosition;
                if (NewGift.Position == null) {
                    calculatedPosition = _GiftList.Gifts == null || _GiftList.Gifts.Count == 0 ?
                        calculatedPosition = 0 :
                        (int) _GiftList.Gifts.Max(gift => gift.Position) + 1;
                }
                else
                {
                    calculatedPosition = (int) NewGift.Position;
                }

                Gift gift = new Gift() {
                    Description = NewGift.Description,
                    InviteCode = inviteCode,
                    IsBought = NewGift.IsBought == null ? NewGift.IsBought : false,
                    Name = NewGift.Name,
                    Position = calculatedPosition
                };
                _context.Gifts.Add(gift);
                _context.SaveChanges();
            }
            return Page();
        }

        public IActionResult OnPostDelete(Gift gift)
        {
            if (ModelState.IsValid)
            {
                if (gift.IsBought == true)
                {
                    _context.Boughts.RemoveRange(
                        _GiftList.Boughts.Where(_bought => _bought.Gift == gift)
                    );
                }
                _context.Gifts.Remove(gift);
                _context.SaveChanges();
            }
            return Page();
        }

        public IActionResult OnPostMoveDown(Gift gift)
        {
            if (ModelState.IsValid)
            {
                List<Gift> gifts = _GiftList.Gifts.ToList();
                Gift switchedGift = gifts[gifts.IndexOf(gift) + 1];
                _context.Gifts.FirstOrDefault(_gift => _gift == gift).Position++;
                _context.Gifts.FirstOrDefault(_gift => _gift == switchedGift).Position--;
                _context.SaveChanges();
            }
            return Page();
        }

        public IActionResult OnPostMoveUp(Gift gift)
        {
            if (ModelState.IsValid)
            {
                List<Gift> gifts = _GiftList.Gifts.ToList();
                Gift switchedGift = gifts[gifts.IndexOf(gift) - 1];
                _context.Gifts.FirstOrDefault(_gift => _gift == gift).Position--;
                _context.Gifts.FirstOrDefault(_gift => _gift == switchedGift).Position++;
                _context.SaveChanges();
            }
            return Page();
        }



    }
}

ASpecialDay/Pages/Index.cshtml.cs
using ASpecialDay.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASpecialDay.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public IndexModel(ILogger<IndexModel> logger, UserManager<Bride> userManager, ASpecialDayContext context)
        {
            _logger = logger;
        }

        public async void OnGet()
        {
        }
    }
}

ASpecialDay/Pages/Invitation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASpecialDay.Pages
{
    public class InvitationModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ASpecialDay/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASpecialDay.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ASpecialDay/Pages/Profile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASpecialDay.Pages
{
    public class ProfileModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ASpecialDay/Pages/GiftList.cshtml
@page "{inviteCode?}"
@using Microsoft.AspNetCore.Identity
@using ASpecialDay.Areas.Identity.Data
@inject SignInManager<Bride> SignInManager
@inject UserManager<Bride> UserManager
@model ASpecialDay.Pages.GiftListModel
@{
    ViewData["Title"] = "GiftList";
}
@section StyleSheets {
    <link rel="stylesheet" href="~/css/gift-list.css" />
}
<!-- Content -->
<div class="container-fluid h-100 p-0 m-0">
    <div class="row h-100 p-0 m-0">
        <div class="col-sm-6 h-100 p-0">
            <span class="wedding-picture h-100 w-100"></span>
            <div class="fixed-bottom position-absolute border-top border-warning p-3"
                 style="background-color: rgba(255, 255, 255, 0.65); clip-path: polygon(0 0, 82.5% 0, 100% 100%, 0 100%);">
                <div class="row">
                    <div class="col">
                        <h4>You've been invited to Sara and Amber their wedding.</h4>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-6">
                        <p>
                            Sarah and Amber have invited you to join their wedding,
                            on this page you will find the wedding info as well as a list of gifts they
                            wish to have. You can cross off the gift you wish to give and leave contact info of
                            you and other participants who'd like to buy the gift together with you.
                        </p>
                    </div>
                    <div class="col-6">
                        <div class="row">
                            <h5>Wedding Information:</h5>
                        </div>
                        <div class="row">
                            <ul class="p-0" style="list-style: none;">
                                <li><i class="far fa-calendar-alt text-warning mr-2"></i>24.04.2021</li>
                                <li><i class="far fa-clock text-warning mr-2"></i>16:30</li>
                                <li><i class="fas fa-map-marker text-warning mr-2"></i>Level 1, Boulevard Tower</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row col-sm-6 h-100 justify-content-center">
            <div class="col-12 my-auto">
                <div class="row">
                    <div class="col-10">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <!-- TODO: Add Validation -->
                            <h3>Add A Wedding Gift:</h3>
                            <div id="add-gift-container" class="mb-2 p-2 border border-secondary rounded bg-white">
                                <div class="row vertically-center p-0">
                                    <form class="form-inline col-12 p-0" method="post" asp-page-handler="AddGift">
                                        <div class="form-group row col-12">
                                            <div class="col-2">
                                                <label class="h5" asp-for="NewGift.Name"></label>
                                            </div>
                                            <div class="col-9">
                                                <input asp-for="NewGift.Name" class="form-control form-text w-100" typeof="text" required />
                                            </div>
                                            <div class="col-1">
                                                <button class="btn btn-outline-secondary" type="submit">
                                                    <i class="fas fa-plus"></i>
                                                </button>
                                            </div>
                                            <input type="hidden" asp-for="InviteCode" value="@Model.InviteCode" />
                                            <span asp-validation-for="NewGift.Name" class="text-danger"></span>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        }
                        <div id="gift-list" class="list-group">
                            <h3>Wedding Gifts Wishlist:</h3>
                            @if (Model._GiftList.Gifts != null)
                            {
                                @foreach (var gift in Model._GiftList.Gifts.Where(gift => gift.IsBought == false))
                                {
                                    <div class="list-group-item">
                                        <h5 class="d-inline">@gift.Name</h5>

                                        @if (SignInManager.IsSignedIn(User))
                                        {
                                            <form method="post" asp-page-handler="MoveDown" asp-route-gift="@gift">
                                                <button class="d-inline float-right">
                                                    <i class="fas fa-arrow-down"></i>
                                                </button>
                                            </form>
                                            <form method="post" asp-page-handler="MoveUp" asp-route-gift="@gift">
                                                <button class="d-inline float-right">
                                                    <i class="fas fa-arrow-up"></i>
                                                </button>
                                            </form>
                                            <form method="post" asp-page-handler="Delete" asp-route-gift="@gift">
                                                <button class="d-inline float-right">
                                                    <i class="fas fa-trash"></i>
                                                </button>
                                            </form>
                                        }
                                        else
                                        {
                                            <!-- TODO: Make popup dialog to add participants -->
                                            <form method="post" asp-page-handler="">
                                                <button class="d-inline float-right">
                                                    <i class="fas fa-check-square"></i>
                                                </button>
                                            </form>
                                        }
                                    </div>
                                }
                            }
                            else
                            {
                                <div class="mb-2 p-2 border border-danger rounded bg-white">
                                    <div class="row vertically-center px-3">
                                        <div class="col-12 text-center">
                                            <h4>No gifts have been added to the list, the list is currently empty.</h4>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                        <!-- TODO: Add Crossed-Off Gift List -->
                    </div>
                </div>
                <div class="row">
                    <div class="col-10">
                        <h3>Crossed-Off Gifts</h3>
                        <div class="list-group">
                            @if (Model._GiftList.Gifts != null)
                            {
                                @foreach (var gift in Model._GiftList.Gifts.Where(gift => gift.IsBought == true))
                                {
                                    <div class="list-group-item">
                                        <h5 class="d-inline">@gift.Name</h5>

                                        @if (SignInManager.IsSignedIn(User))
                                        {
                                            <form method="post" asp-page-handler="Delete" asp-route-gift="@gift">
                                                <button class="d-inline float-right">
                                                    <i class="fas fa-trash"></i>
                                                </button>
                                            </form>
                                        }
                                        else
                                        {

                                        }
                                    </div>
                                }
                            }
                            else
                            {
                                <div class="mb-2 p-2 border border-danger rounded bg-white">
                                    <div class="row vertically-center px-3">
                                        <div class="col-12 text-center">
                                            <h4>No gifts have been crossed-off from list.</h4>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ASpecialDay/Pages/Index.cshtml
@page "{accessCode?}"
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ASpecialDay/Pages/Invitation.cshtml
@page
@model ASpecialDay.Pages.InvitationModel
@{
}

ASpecialDay/Pages/Profile.cshtml
@page
@model ASpecialDay.Pages.ProfileModel
@{
}